version: '3.9'

services:
    api:
        container_name: htain-thein
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mysql_db
        networks:
            - htain-thein-network

    web_server:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - api
        networks:
            - htain-thein-network

    mysql_db:
        image: mysql:latest
        restart: always
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - htain-thein-network

volumes:
    mysql_data:
        driver: local

networks:
    htain-thein-network:
        driver: bridge
