services:
    app:
        container_name: htain-thein
        build:
            context: ./
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        depends_on:
            - mysql_db   # Ensure MySQL container is started first
        networks:
            - htain-thein-network

    mysql_db:
        image: mysql:latest
        container_name: htain-thein-mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Using Docker Compose env vars directly
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - htain-thein-network

    networks:
        htain-thein-network:
            driver: bridge
