<?php

namespace App\Enums;

enum ActivityLogType: string
{
    const USER_CREATE = 'USER_CREATE';
    const USER_UPDATE = 'USER_UPDATE';
    const USER_DELETE = 'USER_DELETE';
    const REPORT_CREATE = 'REPORT_CREATE';
    const REPORT_UPDATE = 'REPORT_UPDATE';
    const REPORT_DELETE = 'REPORT_DELETE';
    const REGULAR_OUTCOME_CREATE = 'REGULAR_OUTCOME_CREATE';
    const REGULAR_OUTCOME_UPDATE = 'REGULAR_OUTCOME_UPDATE';
    const REGULAR_OUTCOME_DELETE = 'REGULAR_OUTCOME_DELETE';
    const ANNOUNCEMENT_CREATE = 'ANNOUNCEMENT_CREATE';
    const ANNOUNCEMENT_UPDATE = 'ANNOUNCEMENT_UPDATE';
    const ANNOUNCEMENT_DELETE = 'ANNOUNCEMENT_DELETE';
}
